kind: pipeline
name: default

steps:
- name: lint
  image: alpine
  commands:
  - apk add --no-cache python3 py3-lxml py3-pip py3-wheel py3-enchant hunspell-en
  - isort --check-only --diff .
  - pip3 install --no-cache-dir .[full] .[dev]
  - pylint morss --rcfile=.pylintrc --disable=C,R,W --fail-under=8
