kind: pipeline
name: default

steps:
- name: lint
  image: alpine
  commands:
  - apk add --no-cache python3 py3-lxml py3-pip py3-wheel py3-enchant hunspell-en
  - pip3 install --no-cache-dir .[full] .[dev]
  - isort --check-only --diff .
  - pylint morss --rcfile=.pylintrc --disable=C,R,W --fail-under=8

- name: pypy
  image: plugins/pypi
  settings:
    username:
      from_secret: pypy_user
    password:
      from_secret: pypy_pwd
  when:
    branch:
    - master
    event:
    - push
