kind: pipeline
name: default

steps:
- name: lint
  image: alpine
  commands:
  - apk add --no-cache python3 py3-lxml py3-pip py3-wheel py3-enchant hunspell-en
  - pip3 install --no-cache-dir .[full] .[dev]
  - isort --check-only --diff .
  - pylint morss --rcfile=.pylintrc --disable=C,R,W --fail-under=8

- name: pypi
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_user
    password:
      from_secret: pypi_pwd
  when:
    branch:
    - master
    event:
    - push

- name: docker
  image: thegeeklab/drone-docker-buildx
  settings:
    username:
      from_secret: docker_user
    password:
      from_secret: docker_pwd
    repo:
      from_secret: docker_repo
    tags: latest
    platforms: linux/amd64,linux/arm64
